import { Entity, PrimaryColumn, Column } from 'typeorm';

export type Gender = 'Male' | 'Female';

@Entity('employees')
export class EmployeeEntity {
  @PrimaryColumn({ type: 'varchar', length: 36 })
  id!: string; // generated by service

  @Column({ type: 'varchar', length: 16, unique: true })
  employeeId!: string; // e.g. JE1234567

  @Column({ type: 'varchar', length: 100 })
  firstName!: string;

  @Column({ type: 'varchar', length: 100 })
  lastName!: string;

  @Column({ type: 'varchar', length: 10 })
  gender!: Gender;

  @Column({ type: 'date', nullable: true })
  dob?: string | null;

  @Column({ type: 'varchar', length: 40, nullable: true })
  phone?: string | null;

  @Column({ type: 'date', nullable: true })
  startDate?: string | null;

  @Column({ type: 'text', nullable: true })
  address?: string | null;

  @Column({ type: 'varchar', length: 120, nullable: true })
  qualification?: string | null;

  @Column({ type: 'decimal', precision: 12, scale: 2, default: 0 })
  salary!: number;

  @Column({ type: 'varchar', length: 50, nullable: true })
  grade?: string | null;

  @Column({ type: 'varchar', length: 64, nullable: true })
  departmentId?: string | null;
}
